version: '3.8'

services:
  db:
    image: postgis/postgis:17-3.4
    container_name: uway
    environment:
      POSTGRES_USER: uway
      POSTGRES_PASSWORD: uway123
      POSTGRES_DB: uway
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-uway
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: uway-web
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    working_dir: /app
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=uway
      - DB_USER=uway
      - DB_PASSWORD=uway123
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db
  frontend:
      build:
        context: ./frontend
        dockerfile: Dockerfile
      container_name: uway-frontend
      command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
      volumes:
        - ./frontend:/app
        - /app/node_modules
      ports:
        - "5173:5173"
      environment:
        - CHOKIDAR_USEPOLLING=true
      depends_on:
        - web

volumes:
  db_data:
  pgadmin_data:
