# Generated by Django 5.2.2 on 2025-06-13 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_minutes', models.PositiveIntegerField(verbose_name='Duration (minutes)')),
                ('distance', models.FloatField(verbose_name='Distance (km)')),
                ('stops', models.PositiveIntegerField(verbose_name='Number of Stops')),
            ],
        ),
    ]
