# Generated by Django 5.2.2 on 2025-06-18 03:26

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_minutes', models.PositiveIntegerField(verbose_name='Duration (minutes)')),
                ('distance', models.FloatField(verbose_name='Distance (km)')),
                ('stops', django.contrib.gis.db.models.fields.LineStringField(srid=4326, verbose_name='Stops Line')),
                ('trip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='trip.trip')),
            ],
        ),
    ]
