# Generated by Django 5.2.2 on 2025-06-21 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_reservation_user_alter_reservation_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='boarded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='has_boarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
