# Generated by Django 5.2.2 on 2025-06-21 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_reservation_boarded_at_reservation_has_boarded_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='reservated_at',
            new_name='reserved_at',
        ),
    ]
