# Generated by Django 5.2.2 on 2025-07-05 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='institutional_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email institucional'),
        ),
    ]
