# Generated by Django 5.2.2 on 2025-06-13 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='addres',
            new_name='address',
        ),
    ]
