# Generated by Django 5.2.2 on 2025-06-12 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('address', models.CharField(max_length=255, verbose_name='Dirección')),
                ('logo_url', models.CharField(blank=True, max_length=255, verbose_name='URL del logo')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='Color principal')),
            ],
        ),
    ]
