# Generated by Django 5.2.2 on 2025-06-12 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('driver', '0002_remove_driver_id_driver_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tecnomecanica', models.URLField(verbose_name='Tecnomecanica Certificate URL')),
                ('model', models.CharField(max_length=100, verbose_name='Model')),
                ('brand', models.CharField(max_length=100, verbose_name='Brand')),
                ('soat', models.URLField(verbose_name='SOAT URL')),
                ('status', models.CharField(max_length=50, verbose_name='Status')),
                ('color', models.CharField(max_length=50, verbose_name='Color')),
                ('plate', models.CharField(max_length=20, verbose_name='Plate')),
                ('category', models.CharField(max_length=50, verbose_name='Category')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='driver.driver')),
            ],
        ),
    ]
