# Generated by Django 5.2.2 on 2025-06-28 03:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='staff', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('staff_code', models.CharField(max_length=100, verbose_name='Código')),
                ('area', models.CharField(max_length=100, verbose_name='Área')),
                ('contract_type', models.CharField(max_length=100, verbose_name='Tipo de contrato')),
                ('location', models.CharField(max_length=100, verbose_name='Sede')),
            ],
        ),
        migrations.DeleteModel(
            name='Administrative_Staff',
        ),
    ]
