# Generated by Django 5.2.2 on 2025-07-26 19:49

import staff.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_staff_delete_administrative_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='staff_card',
            field=models.FileField(blank=True, null=True, upload_to=staff.models.upload_to_staff, verbose_name='staff_card_file'),
        ),
    ]
