# Generated by Django 5.2.2 on 2025-07-26 22:10

import staff.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_staff_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_card',
            field=models.FileField(blank=True, null=True, upload_to=staff.models.upload_to_staff, verbose_name='Carné de Funcionario'),
        ),
    ]
