# Generated by Django 5.2.2 on 2025-06-18 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='student_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('semester', models.CharField(max_length=100, verbose_name='Semestre')),
                ('code', models.CharField(max_length=100, verbose_name='Código')),
                ('is_active', models.CharField(default=True, max_length=100, verbose_name='Activo')),
            ],
        ),
    ]
