# Generated by Django 5.2.2 on 2025-06-28 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=False, max_length=100, verbose_name='Activo'),
        ),
    ]
