# Generated by Django 5.2.2 on 2025-07-26 22:10

import student.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_student_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_card',
            field=models.FileField(blank=True, null=True, upload_to=student.models.upload_to_student, verbose_name='Carné de Estudiante'),
        ),
    ]
