# Generated by Django 5.2.2 on 2025-07-26 19:49

import teacher.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teacher_card',
            field=models.FileField(blank=True, null=True, upload_to=teacher.models.upload_to_teacher, verbose_name='teacher_card_file'),
        ),
    ]
