# Generated by Django 5.2.2 on 2025-07-26 22:10

import teacher.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_teacher_teacher_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_card',
            field=models.FileField(blank=True, null=True, upload_to=teacher.models.upload_to_teacher, verbose_name='Carné de Docente'),
        ),
    ]
