# Generated by Django 5.2.2 on 2025-07-27 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_alter_teacher_is_active_alter_teacher_teacher_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teacher_code',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Código'),
        ),
    ]
