# Generated by Django 5.2.2 on 2025-06-18 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='driver_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('license_number', models.CharField(max_length=50, verbose_name='License Number')),
                ('papers', models.URLField(verbose_name='Papers URL')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Approved')),
            ],
        ),
    ]
