# Generated by Django 5.2.2 on 2025-06-12 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='id',
        ),
        migrations.AddField(
            model_name='driver',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='driver_profile', serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
