# Generated by Django 5.2.2 on 2025-06-28 03:15

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_alter_driver_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='current_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Current Location'),
        ),
    ]
