# Generated by Django 5.2.2 on 2025-06-27 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_alter_driver_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='dni_file',
            field=models.FileField(null=True, upload_to='', verbose_name='DNI File'),
        ),
        migrations.AddField(
            model_name='driver',
            name='driver_license_file',
            field=models.FileField(null=True, upload_to='', verbose_name='Driver License File'),
        ),
        migrations.AddField(
            model_name='driver',
            name='transit_license_file',
            field=models.FileField(null=True, upload_to='', verbose_name='Transit License File'),
        ),
    ]
