# Generated by Django 5.2.2 on 2025-06-27 20:27

import driver.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0003_driver_dni_file_driver_driver_license_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='dni_file',
        ),
        migrations.AddField(
            model_name='driver',
            name='soat_file',
            field=models.FileField(blank=True, null=True, upload_to=driver.models.upload_to_soat, verbose_name='SOAT File'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='driver_license_file',
            field=models.FileField(null=True, upload_to=driver.models.upload_to_driver_license, verbose_name='Driver License File'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='transit_license_file',
            field=models.FileField(null=True, upload_to=driver.models.upload_to_transit_license, verbose_name='Transit License File'),
        ),
    ]
