# Generated by Django 5.2.2 on 2025-06-28 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0003_driver_current_location'),
        ('driver', '0004_remove_driver_dni_file_driver_soat_file_and_more'),
    ]

    operations = [
    ]
