# Generated by Django 5.2.2 on 2025-06-28 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0005_merge_20250628_1703'),
        ('driver', '0005_merge_20250628_1720'),
    ]

    operations = [
    ]
