# Generated by Django 5.2.2 on 2025-07-17 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0006_merge_20250628_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='papers',
            field=models.URLField(blank=True, null=True, verbose_name='Papers URL'),
        ),
    ]
