# Generated by Django 5.2.2 on 2025-06-18 03:26

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_point', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Start Point')),
                ('end_point', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='End Point')),
                ('qr_url', models.URLField(blank=True, verbose_name='QR Code URL')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='vehicle.vehicle')),
            ],
        ),
    ]
