# Generated by Django 5.2.2 on 2025-06-28 01:21

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_trip_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='distance',
            field=models.FloatField(blank=True, null=True, verbose_name='Distance (km)'),
        ),
        migrations.AddField(
            model_name='trip',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Duration (minutes)'),
        ),
        migrations.AddField(
            model_name='trip',
            name='route',
            field=django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326, verbose_name='Route Geometry'),
        ),
    ]
