# Generated by Django 5.2.2 on 2025-06-28 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0003_trip_distance_trip_duration_trip_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='route_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Full OSRM response'),
        ),
    ]
