# Generated by Django 5.2.2 on 2025-06-28 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0004_trip_route_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='route_data',
        ),
    ]
