# Generated by Django 5.2.2 on 2025-06-28 02:29

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0005_remove_trip_route_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='route',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, null=True, srid=4326, verbose_name='Route Geometry'),
        ),
    ]
