# Generated by Django 5.2.2 on 2025-06-28 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0006_alter_trip_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hora de inicio (km)'),
        ),
    ]
