# Generated by Django 5.2.2 on 2025-06-28 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0008_alter_trip_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='deviation_detected',
            field=models.BooleanField(default=False),
        ),
    ]
