# Generated by Django 5.2.2 on 2025-07-24 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0009_trip_deviation_detected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='end_point',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='start_point',
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='scheduled', max_length=20),
        ),
    ]
